# Generated by Django 3.0.4 on 2020-03-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_username', models.CharField(max_length=200)),
                ('param_password', models.CharField(max_length=200)),
                ('url_connection', models.CharField(max_length=200)),
                ('param_herb', models.CharField(max_length=200)),
                ('param_drug', models.CharField(max_length=200)),
                ('url_results', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hedrine',
            fields=[
                ('database_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.Database')),
            ],
            bases=('search.database',),
        ),
        migrations.CreateModel(
            name='MSKCC',
            fields=[
                ('database_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.Database')),
            ],
            bases=('search.database',),
        ),
    ]
